name: CI

on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.1
          elixir-version: 1.14.0

      - name: Install dependencies
        run: mix deps.get

      - name: Check mix format
        run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.1
          elixir-version: 1.14.0

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Check for compiler warnings
        run: |
          MIX_ENV=test mix compile --warnings-as-errors

      - name: Run tests
        run: |
          mix test
